version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'

  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./authServer 
    volumes: 
      - /app/node_modules
      - ./authServer:/app
      
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
      
  # worker:
  #   environment:
  #   - REDIS_HOST=redis
  #   - REDIS_PORT=6379
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes: 
  #     - /app/node_modules
  #     - ./worker:/app
  