version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'

  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./authServer 
    volumes: 
      - /app/node_modules
      - ./authServer:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true

  profile:
    build: 
      dockerfile: Dockerfile.dev
      context: ./profileServer 
    volumes: 
      - /app/node_modules
      - ./profileServer:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true

  core:
    build: 
      dockerfile: Dockerfile.dev
      context: ./coreServer 
    volumes: 
      - /app/node_modules
      - ./coreServer:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true

  filter:
    build: 
      dockerfile: Dockerfile.dev
      context: ./filterServer 
    volumes: 
      - /app/node_modules
      - ./filterServer:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true

  tuning:
    build: 
      dockerfile: Dockerfile.dev
      context: ./tuningServer 
    volumes: 
      - /app/node_modules
      - ./tuningServer:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true

  retuning:
    build: 
      dockerfile: Dockerfile.dev
      context: ./retuningServer 
    volumes: 
      - /app/node_modules
      - ./retuningServer:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
      
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  
  # worker:
  #   environment:
  #   - REDIS_HOST=redis
  #   - REDIS_PORT=6379
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes: 
  #     - /app/node_modules
  #     - ./worker:/app
  